services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: CompetencyGraph-Web
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

