services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: CompetencyGraph-Web
    ports:
      - "5173:5173"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
