services:
  dev:
    image: node:22.17.0
    container_name: project-graph-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev -- --host"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

